#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TwittersList.Droid.Resource", IsApplication=true)]

namespace TwittersList.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int my_blue = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int my_gray = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int my_green = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int my_purple = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bulbs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CustomSelector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int FlowerBuds = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Fruits = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Legumes = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Tubers = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Vegetables = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int HotDotImageView = 2131230729;
			
			// aapt resource value: 0x7f080003
			public const int Image = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int Text = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Text1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int Text2 = 2131230722;
			
			// aapt resource value: 0x7f08000c
			public const int btnAcept = 2131230732;
			
			// aapt resource value: 0x7f080018
			public const int btnAdd = 2131230744;
			
			// aapt resource value: 0x7f08000d
			public const int btnCancel = 2131230733;
			
			// aapt resource value: 0x7f080019
			public const int btnDelete = 2131230745;
			
			// aapt resource value: 0x7f080011
			public const int btnLlamar = 2131230737;
			
			// aapt resource value: 0x7f080006
			public const int button1 = 2131230726;
			
			// aapt resource value: 0x7f08000f
			public const int frmFragment = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int frmFragment1 = 2131230736;
			
			// aapt resource value: 0x7f080008
			public const int imageView1 = 2131230728;
			
			// aapt resource value: 0x7f080017
			public const int linearLayout1 = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int lstList = 2131230746;
			
			// aapt resource value: 0x7f080007
			public const int lstViewMenu = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int myButton = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int progressBar1 = 2131230725;
			
			// aapt resource value: 0x7f08001b
			public const int rayPictureImageView = 2131230747;
			
			// aapt resource value: 0x7f080015
			public const int spnCategory = 2131230741;
			
			// aapt resource value: 0x7f08001c
			public const int takePictureButton = 2131230748;
			
			// aapt resource value: 0x7f080013
			public const int textView1 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int textView2 = 2131230740;
			
			// aapt resource value: 0x7f08000b
			public const int txtDescription = 2131230731;
			
			// aapt resource value: 0x7f080016
			public const int txtExpense = 2131230742;
			
			// aapt resource value: 0x7f080012
			public const int txtFinalMsg = 2131230738;
			
			// aapt resource value: 0x7f08000e
			public const int txtMsg = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public const int txtName = 2131230730;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CustomView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int MenuFragment = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int PrincipalFragment = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Screen1 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Screen2 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Screen3 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int SqlActivityView = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int TakePictureView = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyCustomTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
