#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TwittersList.Droid.Resource", IsApplication=true)]

namespace TwittersList.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Bulbs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CustomSelector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int FlowerBuds = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Fruits = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Legumes = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Tubers = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Vegetables = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int HotDotImageView = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int Image = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int Text = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Text1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Text2 = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int btnAcept = 2131099660;
			
			// aapt resource value: 0x7f060018
			public const int btnAdd = 2131099672;
			
			// aapt resource value: 0x7f06000d
			public const int btnCancel = 2131099661;
			
			// aapt resource value: 0x7f060019
			public const int btnDelete = 2131099673;
			
			// aapt resource value: 0x7f060011
			public const int btnLlamar = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int button1 = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int frmFragment = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int frmFragment1 = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int imageView1 = 2131099656;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout1 = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int lstList = 2131099674;
			
			// aapt resource value: 0x7f060007
			public const int lstViewMenu = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int myButton = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int progressBar1 = 2131099653;
			
			// aapt resource value: 0x7f06001b
			public const int rayPictureImageView = 2131099675;
			
			// aapt resource value: 0x7f060015
			public const int spnCategory = 2131099669;
			
			// aapt resource value: 0x7f06001c
			public const int takePictureButton = 2131099676;
			
			// aapt resource value: 0x7f060013
			public const int textView1 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int textView2 = 2131099668;
			
			// aapt resource value: 0x7f06000b
			public const int txtDescription = 2131099659;
			
			// aapt resource value: 0x7f060016
			public const int txtExpense = 2131099670;
			
			// aapt resource value: 0x7f060012
			public const int txtFinalMsg = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int txtMsg = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int txtName = 2131099658;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CustomView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int MenuFragment = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int PrincipalFragment = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Screen1 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Screen2 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Screen3 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int SqlActivityView = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int TakePictureView = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
