#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TwittersList.Droid.Resource", IsApplication=true)]

namespace TwittersList.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Auth0.OidcClient.Resource.String.ApplicationName = global::TwittersList.Droid.Resource.String.ApplicationName;
			global::Auth0.OidcClient.Resource.String.Hello = global::TwittersList.Droid.Resource.String.Hello;
			global::LoginScreen.Resource.Drawable.alert = global::TwittersList.Droid.Resource.Drawable.alert;
			global::LoginScreen.Resource.Drawable.arrow = global::TwittersList.Droid.Resource.Drawable.arrow;
			global::LoginScreen.Resource.Drawable.bg_login = global::TwittersList.Droid.Resource.Drawable.bg_login;
			global::LoginScreen.Resource.Drawable.button_login = global::TwittersList.Droid.Resource.Drawable.button_login;
			global::LoginScreen.Resource.Drawable.button_login_pressed = global::TwittersList.Droid.Resource.Drawable.button_login_pressed;
			global::LoginScreen.Resource.Drawable.button_login_selector = global::TwittersList.Droid.Resource.Drawable.button_login_selector;
			global::LoginScreen.Resource.Drawable.button_register = global::TwittersList.Droid.Resource.Drawable.button_register;
			global::LoginScreen.Resource.Drawable.button_register_pressed = global::TwittersList.Droid.Resource.Drawable.button_register_pressed;
			global::LoginScreen.Resource.Drawable.button_register_selector = global::TwittersList.Droid.Resource.Drawable.button_register_selector;
			global::LoginScreen.Resource.Drawable.button_reset = global::TwittersList.Droid.Resource.Drawable.button_reset;
			global::LoginScreen.Resource.Drawable.button_reset_pressed = global::TwittersList.Droid.Resource.Drawable.button_reset_pressed;
			global::LoginScreen.Resource.Drawable.button_reset_selector = global::TwittersList.Droid.Resource.Drawable.button_reset_selector;
			global::LoginScreen.Resource.Drawable.divider_bottom = global::TwittersList.Droid.Resource.Drawable.divider_bottom;
			global::LoginScreen.Resource.Drawable.divider_top = global::TwittersList.Droid.Resource.Drawable.divider_top;
			global::LoginScreen.Resource.Drawable.edittext_bg_selector = global::TwittersList.Droid.Resource.Drawable.edittext_bg_selector;
			global::LoginScreen.Resource.Drawable.edittext_textcolor_selector = global::TwittersList.Droid.Resource.Drawable.edittext_textcolor_selector;
			global::LoginScreen.Resource.Drawable.Icon = global::TwittersList.Droid.Resource.Drawable.Icon;
			global::LoginScreen.Resource.Drawable.image_password = global::TwittersList.Droid.Resource.Drawable.image_password;
			global::LoginScreen.Resource.Drawable.image_password_active = global::TwittersList.Droid.Resource.Drawable.image_password_active;
			global::LoginScreen.Resource.Drawable.image_username = global::TwittersList.Droid.Resource.Drawable.image_username;
			global::LoginScreen.Resource.Drawable.image_username_active = global::TwittersList.Droid.Resource.Drawable.image_username_active;
			global::LoginScreen.Resource.Drawable.password_right_selector = global::TwittersList.Droid.Resource.Drawable.password_right_selector;
			global::LoginScreen.Resource.Drawable.textfield = global::TwittersList.Droid.Resource.Drawable.textfield;
			global::LoginScreen.Resource.Drawable.textfield_active = global::TwittersList.Droid.Resource.Drawable.textfield_active;
			global::LoginScreen.Resource.Drawable.username_right_selector = global::TwittersList.Droid.Resource.Drawable.username_right_selector;
			global::LoginScreen.Resource.Id.bottomSpace = global::TwittersList.Droid.Resource.Id.bottomSpace;
			global::LoginScreen.Resource.Id.confirmPasswordEdit = global::TwittersList.Droid.Resource.Id.confirmPasswordEdit;
			global::LoginScreen.Resource.Id.emailEdit = global::TwittersList.Droid.Resource.Id.emailEdit;
			global::LoginScreen.Resource.Id.errorLayout = global::TwittersList.Droid.Resource.Id.errorLayout;
			global::LoginScreen.Resource.Id.errorMessage = global::TwittersList.Droid.Resource.Id.errorMessage;
			global::LoginScreen.Resource.Id.fake = global::TwittersList.Droid.Resource.Id.fake;
			global::LoginScreen.Resource.Id.forgotLayout = global::TwittersList.Droid.Resource.Id.forgotLayout;
			global::LoginScreen.Resource.Id.forgotText = global::TwittersList.Droid.Resource.Id.forgotText;
			global::LoginScreen.Resource.Id.loginButton = global::TwittersList.Droid.Resource.Id.loginButton;
			global::LoginScreen.Resource.Id.loginEdit = global::TwittersList.Droid.Resource.Id.loginEdit;
			global::LoginScreen.Resource.Id.loginLayout = global::TwittersList.Droid.Resource.Id.loginLayout;
			global::LoginScreen.Resource.Id.loginText = global::TwittersList.Droid.Resource.Id.loginText;
			global::LoginScreen.Resource.Id.noAccountImage = global::TwittersList.Droid.Resource.Id.noAccountImage;
			global::LoginScreen.Resource.Id.noAccountSection = global::TwittersList.Droid.Resource.Id.noAccountSection;
			global::LoginScreen.Resource.Id.noAccountText = global::TwittersList.Droid.Resource.Id.noAccountText;
			global::LoginScreen.Resource.Id.passwordEdit = global::TwittersList.Droid.Resource.Id.passwordEdit;
			global::LoginScreen.Resource.Id.registerButton = global::TwittersList.Droid.Resource.Id.registerButton;
			global::LoginScreen.Resource.Id.registerText = global::TwittersList.Droid.Resource.Id.registerText;
			global::LoginScreen.Resource.Id.resetButton = global::TwittersList.Droid.Resource.Id.resetButton;
			global::LoginScreen.Resource.Id.resetText = global::TwittersList.Droid.Resource.Id.resetText;
			global::LoginScreen.Resource.Id.rootLayout = global::TwittersList.Droid.Resource.Id.rootLayout;
			global::LoginScreen.Resource.Id.titleLayout = global::TwittersList.Droid.Resource.Id.titleLayout;
			global::LoginScreen.Resource.Layout.a_login = global::TwittersList.Droid.Resource.Layout.a_login;
			global::LoginScreen.Resource.Layout.a_register = global::TwittersList.Droid.Resource.Layout.a_register;
			global::LoginScreen.Resource.Layout.a_reset = global::TwittersList.Droid.Resource.Layout.a_reset;
			global::LoginScreen.Resource.Layout.a_validationerror = global::TwittersList.Droid.Resource.Layout.a_validationerror;
			global::LoginScreen.Resource.String.library_name = global::TwittersList.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int my_blue = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int my_gray = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int my_green = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int my_purple = 2131099650;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int alert = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_login = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Bulbs = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_login = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_login_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_login_selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_register = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_register_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_register_selector = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int button_reset = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button_reset_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int button_reset_selector = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int CustomSelector = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int divider_bottom = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int divider_top = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int edittext_bg_selector = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int edittext_textcolor_selector = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int FlowerBuds = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Fruits = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int image_password = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int image_password_active = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int image_username = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int image_username_active = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Legumes = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int password_right_selector = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int textfield = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int textfield_active = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Tubers = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int username_right_selector = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Vegetables = 2130837535;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001f
			public const int HotDotImageView = 2131230751;
			
			// aapt resource value: 0x7f080019
			public const int Image = 2131230745;
			
			// aapt resource value: 0x7f080016
			public const int Text = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int Text1 = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int Text2 = 2131230744;
			
			// aapt resource value: 0x7f08000d
			public const int bottomSpace = 2131230733;
			
			// aapt resource value: 0x7f080022
			public const int btnAcept = 2131230754;
			
			// aapt resource value: 0x7f08002e
			public const int btnAdd = 2131230766;
			
			// aapt resource value: 0x7f080023
			public const int btnCancel = 2131230755;
			
			// aapt resource value: 0x7f08002f
			public const int btnDelete = 2131230767;
			
			// aapt resource value: 0x7f080027
			public const int btnLlamar = 2131230759;
			
			// aapt resource value: 0x7f08001c
			public const int button1 = 2131230748;
			
			// aapt resource value: 0x7f080011
			public const int confirmPasswordEdit = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int emailEdit = 2131230736;
			
			// aapt resource value: 0x7f080014
			public const int errorLayout = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int errorMessage = 2131230741;
			
			// aapt resource value: 0x7f080008
			public const int fake = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int forgotLayout = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int forgotText = 2131230727;
			
			// aapt resource value: 0x7f080025
			public const int frmFragment = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int frmFragment1 = 2131230758;
			
			// aapt resource value: 0x7f08001e
			public const int imageView1 = 2131230750;
			
			// aapt resource value: 0x7f08002d
			public const int linearLayout1 = 2131230765;
			
			// aapt resource value: 0x7f080005
			public const int loginButton = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int loginEdit = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int loginLayout = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int loginText = 2131230722;
			
			// aapt resource value: 0x7f080030
			public const int lstList = 2131230768;
			
			// aapt resource value: 0x7f08001d
			public const int lstViewMenu = 2131230749;
			
			// aapt resource value: 0x7f08001a
			public const int myButton = 2131230746;
			
			// aapt resource value: 0x7f08000a
			public const int noAccountImage = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int noAccountSection = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int noAccountText = 2131230731;
			
			// aapt resource value: 0x7f080004
			public const int passwordEdit = 2131230724;
			
			// aapt resource value: 0x7f08001b
			public const int progressBar1 = 2131230747;
			
			// aapt resource value: 0x7f080031
			public const int rayPictureImageView = 2131230769;
			
			// aapt resource value: 0x7f08000c
			public const int registerButton = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int registerText = 2131230735;
			
			// aapt resource value: 0x7f080013
			public const int resetButton = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int resetText = 2131230738;
			
			// aapt resource value: 0x7f080000
			public const int rootLayout = 2131230720;
			
			// aapt resource value: 0x7f08002b
			public const int spnCategory = 2131230763;
			
			// aapt resource value: 0x7f080032
			public const int takePictureButton = 2131230770;
			
			// aapt resource value: 0x7f080029
			public const int textView1 = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int textView2 = 2131230762;
			
			// aapt resource value: 0x7f08000e
			public const int titleLayout = 2131230734;
			
			// aapt resource value: 0x7f080021
			public const int txtDescription = 2131230753;
			
			// aapt resource value: 0x7f08002c
			public const int txtExpense = 2131230764;
			
			// aapt resource value: 0x7f080028
			public const int txtFinalMsg = 2131230760;
			
			// aapt resource value: 0x7f080024
			public const int txtMsg = 2131230756;
			
			// aapt resource value: 0x7f080020
			public const int txtName = 2131230752;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int a_login = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int a_register = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int a_reset = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int a_validationerror = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int CustomView = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Main = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int MenuFragment = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int PrincipalFragment = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Screen1 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Screen2 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Screen3 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int SqlActivityView = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int TakePictureView = 2130968588;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int app_name = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int hello = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyCustomTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
